import { createI18n } from 'vue-i18n'
import { LanguageCode } from './courses/languageMetadata'

export const i18nDefinition = createI18n({
  locale: 'en',
  fallbackLocale: 'en',
  legacy: false,
  messages: {
    en: {
      mainTitle: 'Duolingo Goal Calculator',
      mainForm: {
        sourceLang: 'I am learning from',
        course: 'Course',
        section: 'Section',
        unit: 'Unit'
      },
      changeLanguage: 'Change Language!',
      lang: {
        [LanguageCode.English]: 'English',
        [LanguageCode.EnglishIntermediate]: 'Intermediate English',
        [LanguageCode.Zulu]: 'Zulu',
        [LanguageCode.Chinese]: 'Chinese',
        [LanguageCode.Yiddish]: 'Yiddish',
        [LanguageCode.Vietnamese]: 'Vietnamese',
        [LanguageCode.Ukrainian]: 'Ukrainian',
        [LanguageCode.Turkish]: 'Turkish',
        [LanguageCode.Swahili]: 'Swahili',
        [LanguageCode.Swedish]: 'Swedish',
        [LanguageCode.Russian]: 'Russian',
        [LanguageCode.Romanian]: 'Romanian',
        [LanguageCode.Polish]: 'Polish',
        [LanguageCode.Portuguese]: 'Portuguese',
        [LanguageCode.Navajo]: 'Navajo',
        [LanguageCode.Dutch]: 'Dutch',
        [LanguageCode.Norwegian]: 'Norwegian',
        [LanguageCode.Latin]: 'Latin',
        [LanguageCode.Korean]: 'Korean',
        [LanguageCode.Klingon]: 'Klingon',
        [LanguageCode.Japanese]: 'Japanese',
        [LanguageCode.Italian]: 'Italian',
        [LanguageCode.Indonesian]: 'Indonesian',
        [LanguageCode.Hawaiian]: 'Hawaiian',
        [LanguageCode.HighValyrian]: 'High Valyrian',
        [LanguageCode.Hungarian]: 'Hungarian',
        [LanguageCode.HaitianCreole]: 'Haitian Creole',
        [LanguageCode.Hindi]: 'Hindi',
        [LanguageCode.Hebrew]: 'Hebrew',
        [LanguageCode.ScottishGaelic]: 'Scottish Gaelic',
        [LanguageCode.Irish]: 'Irish',
        [LanguageCode.French]: 'French',
        [LanguageCode.Finnish]: 'Finnish',
        [LanguageCode.Esperanto]: 'Esperanto',
        [LanguageCode.Spanish]: 'Spanish',
        [LanguageCode.Greek]: 'Greek',
        [LanguageCode.German]: 'German',
        [LanguageCode.Danish]: 'Danish',
        [LanguageCode.Welsh]: 'Welsh',
        [LanguageCode.Czech]: 'Czech',
        [LanguageCode.Arabic]: 'Arabic',
        [LanguageCode.Cantonese]: 'Cantonese',
        [LanguageCode.Catalan]: 'Catalan',
        [LanguageCode.Thai]: 'Thai',
        [LanguageCode.Telugu]: 'Telugu',
        [LanguageCode.Filipino]: 'Filipino',
        [LanguageCode.Bengali]: 'Bengali'
      }
    },
    es: {
      mainTitle: 'Calculadora de objetivos de Duolingo',
      mainForm: {
        sourceLang: 'Estoy aprendiendo de',
        course: 'Curso',
        section: 'Sección',
        unit: 'Unidad'
      },
      changeLanguage: '¡Cambia de idioma!',
      lang: {
        [LanguageCode.English]: 'Inglés',
        [LanguageCode.EnglishIntermediate]: 'Inglés intermedio',
        [LanguageCode.Zulu]: 'Zulú',
        [LanguageCode.Chinese]: 'Chino',
        [LanguageCode.Yiddish]: 'Yiddish',
        [LanguageCode.Vietnamese]: 'Vietnamita',
        [LanguageCode.Ukrainian]: 'Ucraniano',
        [LanguageCode.Turkish]: 'Turco',
        [LanguageCode.Swahili]: 'Swahili',
        [LanguageCode.Swedish]: 'sueco',
        [LanguageCode.Russian]: 'ruso',
        [LanguageCode.Romanian]: 'rumano',
        [LanguageCode.Polish]: 'polaco',
        [LanguageCode.Portuguese]: 'portugués',
        [LanguageCode.Navajo]: 'navajo',
        [LanguageCode.Dutch]: 'holandés',
        [LanguageCode.Norwegian]: 'noruego',
        [LanguageCode.Latin]: 'latín',
        [LanguageCode.Korean]: 'coreano',
        [LanguageCode.Klingon]: 'klingon',
        [LanguageCode.Japanese]: 'japonés',
        [LanguageCode.Italian]: 'italiano',
        [LanguageCode.Indonesian]: 'indonesio',
        [LanguageCode.Hawaiian]: 'hawaiano',
        [LanguageCode.HighValyrian]: 'alto valyrio',
        [LanguageCode.Hungarian]: 'húngaro',
        [LanguageCode.HaitianCreole]: 'criollo haitiano',
        [LanguageCode.Hindi]: 'hindi',
        [LanguageCode.Hebrew]: 'hebreo',
        [LanguageCode.ScottishGaelic]: 'gaélico escocés',
        [LanguageCode.Irish]: 'irlandés',
        [LanguageCode.French]: 'francés',
        [LanguageCode.Finnish]: 'finlandés',
        [LanguageCode.Esperanto]: 'esperanto',
        [LanguageCode.Spanish]: 'Español',
        [LanguageCode.Greek]: 'Griego',
        [LanguageCode.German]: 'Alemán',
        [LanguageCode.Danish]: 'Danés',
        [LanguageCode.Welsh]: 'Galés',
        [LanguageCode.Czech]: 'Checo',
        [LanguageCode.Arabic]: 'Árabe',
        [LanguageCode.Cantonese]: 'Cantonés',
        [LanguageCode.Catalan]: 'Catalán',
        [LanguageCode.Thai]: 'Tailandés',
        [LanguageCode.Telugu]: 'Telugu',
        [LanguageCode.Filipino]: 'Filipino',
        [LanguageCode.Bengali]: 'Bengalí'
      }
    }
  }
})
